Initial contribution: tW @ 5 TeV
uniovi-hepex/xuAnalysis pull request #6
Opened 2020-03-11 11:23 UTC by vrbouza

Initial code for doing the analysis for tW @ 5 TeV. Not yet ready.

2020-03-30 16:41 UTC, vrbouza commented
Now ready to merge.

2020-03-31 05:43 UTC, folguera approved these changes

2020-03-31 05:45 UTC, folguera requested changes
@vrbouza no necesitas los pdfs de los scale factors, no?

2020-03-31 10:51 UTC, folguera approved these changes

2020-03-31 10:51 UTC, merged